# Site settings
title: 汪晓东 - Shallker Wang
email: shallker.wang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   前端研发工程师一枚，拥抱WebApp，开源项目贡献者，目前工作在百度。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shallker.github.io" # the base hostname & protocol for your site
twitter_username: shallker
github_username:  shallker

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
